version: "3.7"

services:
    # image project
    assinador-digital-web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - assinador-digital-web

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - assinador-digital-web

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-assinador-digital-web}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "9003:3306"
        networks:
            - assinador-digital-web

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "9002:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - assinador-digital-web

    # redis
    redis:
        image: redis:latest
        networks:
            - assinador-digital-web

networks:
    assinador-digital-web:
        driver: bridge